# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd Cookta-online
    npm install -g @angular/cli
    npm install
    npm install firebase -g
    ng build --prod
    firebase deploy --token 1/yZ3Yrn_Zt2ZhH9AmPtlXciYt-1x00VOzF3iIHLb4X6I
  displayName: 'npm install and build'
