import {Controller} from 'waxen/dist/deorators/controller';
import {Contracts} from 'cookta-shared/src/contracts/contracts';
import {ICreateReportRequest} from 'cookta-shared/src/contracts/reports/create-report.request.interface';

@Controller(Contracts.Reports)
export class ReportController {
    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async GetReports(reqBody: void): Promise<void> {
        throw new Error('Route GetReports is not implemented');
    }

    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async DeleteReport(reqBody: void, id: string): Promise<void> {
        throw new Error('Route DeleteReport is not implemented');
    }

    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async ResolveReport(reqBody: void, id: string): Promise<void> {
        throw new Error('Route ResolveReport is not implemented');
    }

    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async CreateReport(reqBody: ICreateReportRequest): Promise<void> {
        throw new Error('Route CreateReport is not implemented');
    }
}
