import {ClassDeclaration, Scope} from "ts-morph";
import {IGeneratorController} from "../../extensions/generator-controller.interface";
import {ControllerData} from "waxen/dist/abstract/controller.interface";


function GenerateRouteFunctions(controllerInfo: IGeneratorController, controller: ClassDeclaration){
    for (let routeInfo of controllerInfo.routes) {
        let method = controller.getMethod(routeInfo.routeName);
        let parameters = [
            {name: 'reqBody', type: routeInfo.requestTypeName}]
            .concat(routeInfo.paramTypeOrder.map((p) => {
                return {name: p.key, type: p.type}
            }));
        let returnType = 'Promise<' + routeInfo.responseTypeName + '>';

        if (!method) {
            controller.addMethod({
                isAbstract: false,
                docs: ['TODO This method is auto generated by waxen generator. Please end it.'],
                isAsync: true,
                name: routeInfo.routeName,
                statements: [`throw new Error('Route ${routeInfo.routeName} is not implemented');`],
                parameters: parameters,
                returnType: returnType,
                scope: Scope.Public
            });
        } else {
            method.setIsAbstract(false);
            method.setIsAsync(true);
            method.getParameters().forEach(p => p.remove());
            method.addParameters(parameters);
            method.setReturnType(returnType);
            method.setScope(Scope.Public);
        }
    }
}

export function GenerateController(controller: ClassDeclaration, controllerInfo: IGeneratorController): IGeneratorController {
    console.log('Generating ' + controller.getName() + '....');
    try {
        controllerInfo.className = controller.getName();
        GenerateRouteFunctions(controllerInfo, controller);
        controller.formatText();
        controller.getSourceFile().saveSync();
        return controllerInfo;
    } catch (error) {
        console.error(error);
        console.log(controller.getName() + ' could not be generated.');
    }
}
