# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    checkLatest: true
  displayName: 'Install Node.js'
  
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Cookta-server'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'Cookta-server'
    customCommand: 'run build'
  displayName: 'Build'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'Cookta-server'
    customCommand: 'test'
  displayName: 'Unit Test'
  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go (9fd6c1a9-9825-4d62-a68c-0907996e5a5c)'
    appType: 'webApp'
    WebAppName: 'cooktaservices'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'