import {Controller} from "waxen/dist/deorators/controller";
import {Contracts} from "cookta-shared/src/contracts/contracts";
import { IRole } from "cookta-shared/src/models/roles/role.interface";

@Controller(Contracts.Roles)
export class RoleController {
    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async GetRoles(reqBody: void): Promise<IRole[]> {
        throw new Error('Route GetRoles is not implemented');
    }

    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async SetRole(reqBody: IRole): Promise<{ success: boolean, edited: IRole }> {
        throw new Error('Route SetRole is not implemented');
    }

    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async CreateRole(reqBody: IRole): Promise<{ created: IRole }> {
        throw new Error('Route CreateRole is not implemented');
    }

    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async DeleteRole(reqBody: void, roleId: string, changeRoleTo: string): Promise<{ changed: string }> {
        throw new Error('Route DeleteRole is not implemented');
    }
}
