import {Services} from "../Services";
import {Food} from "../models/food/food.model";
import {IBadUnit} from "cookta-shared/src/models/unit/bad-unit.interface";
import {Controller} from "waxen/dist/deorators/controller";
import {Contracts} from 'cookta-shared/src/contracts/contracts';
import {Security} from "waxen/dist/deorators/security";
import {IUnit} from "cookta-shared/src/models/unit/unit.interface";
import {FixBadUnitRequest, GetBadUnitResponse} from "cookta-shared/src/contracts/unit-route/get-bad-units";

@Controller(Contracts.Units)
export class UnitController {

    public async GetAll(reqBody: void): Promise<IUnit[]> {
        return Services.UnitService.GetAllItems();
    }

    @Security(false, 'advanced-ingredients')
    public async GetBedUnits(): Promise<any> {
        let foods = await Food.GetAllFoods({});
        let unitRefs: IBadUnit[] = await Services.UnitService.GetBadUnitReferences(
            Services.EssentialsService.GetAllItems(),
            Services.StorageService.GetAllItems(),
            foods);
        return { badUnits: unitRefs };
    }

    //Should return the remaining unit list.
    @Security(false, 'advanced-ingredients')
    public async FixBedUnit(reqBody: any): Promise<any> {
        let foods: Food[] = [];
        foods = await Food.GetAllFoods({});
        if (reqBody.badUnit.Fix && reqBody.badUnit.FixUnit) {
            let ingredientType = Services.IngredientTypeService.FindOne(i => i.guid == reqBody.badUnit.IngredientId);
            let fixUnit = Services.UnitService.GetAvailableUnitsForType(ingredientType).find(u => u.id == reqBody.badUnit.FixUnit);

            await Services.UnitService.FixBadUnit(
                reqBody.badUnit.UnitId,
                reqBody.badUnit.IngredientId,
                fixUnit,
                reqBody.badUnit.Fix,
                Services.EssentialsService.GetAllItems(),
                Services.StorageService.GetAllItems(),
                foods);
        }

        return {
            badUnits: await Services.UnitService.GetBadUnitReferences(
                Services.EssentialsService.GetAllItems(),
                Services.StorageService.GetAllItems(),
                foods)
        };
    }

    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async GetBadUnits(reqBody: void): Promise<GetBadUnitResponse> {
        throw new Error('Route GetBadUnits is not implemented');
    }

    /** TODO This method is auto generated by waxen generator. Please end it. */
    public async FixBadUnit(reqBody: FixBadUnitRequest): Promise<GetBadUnitResponse> {
        throw new Error('Route FixBadUnit is not implemented');
    }
}
